"""add claimed_at to dedup_executions for concurrency exclusivity

Revision ID: 02467162321c
Revises: 6189c90d31a8
Create Date: 2026-09-12 18:35:04.836869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02467162321c'
down_revision: Union[str, Sequence[str], None] = '6189c90d31a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dedup_executions', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dedup_executions', 'claimed_at')
    # ### end Alembic commands ###
