"""add dedup execution audit tables

Revision ID: 16a7cf136058
Revises: d0ac67db7d95
Create Date: 2026-09-12 15:40:47.745925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '16a7cf136058'
down_revision: Union[str, Sequence[str], None] = 'd0ac67db7d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedup_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorization_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'PARTIALLY_COMPLETED', name='dedup_execution_status'), server_default='RUNNING', nullable=False),
    sa.Column('executor_identity', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authorization_id'], ['dedup_plan_authorizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['dedup_execution_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_id', name='uq_dedup_executions_authorization_id')
    )
    op.create_index(op.f('ix_dedup_executions_authorization_id'), 'dedup_executions', ['authorization_id'], unique=False)
    op.create_index(op.f('ix_dedup_executions_id'), 'dedup_executions', ['id'], unique=False)
    op.create_index(op.f('ix_dedup_executions_plan_id'), 'dedup_executions', ['plan_id'], unique=False)
    op.create_table('dedup_execution_action_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('plan_action_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('planned_action', postgresql.ENUM('DELETE', name='dedup_plan_action_type', create_type=False), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('target_path', sa.Text(), nullable=False),
    sa.Column('expected_content_hash', sa.String(length=64), nullable=True),
    sa.Column('expected_file_size', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'PRECONDITION_FAILED', 'FAILED', 'NOT_ATTEMPTED', name='dedup_execution_action_result'), nullable=False),
    sa.Column('observed_content_hash', sa.String(length=64), nullable=True),
    sa.Column('observed_file_size', sa.Integer(), nullable=True),
    sa.Column('filesystem_mutation_occurred', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['dedup_executions.id'], ),
    sa.ForeignKeyConstraint(['plan_action_id'], ['dedup_execution_plan_actions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'plan_action_id', name='uq_dedup_execution_action_audits_execution_id_plan_action_id')
    )
    op.create_index(op.f('ix_dedup_execution_action_audits_document_id'), 'dedup_execution_action_audits', ['document_id'], unique=False)
    op.create_index(op.f('ix_dedup_execution_action_audits_execution_id'), 'dedup_execution_action_audits', ['execution_id'], unique=False)
    op.create_index(op.f('ix_dedup_execution_action_audits_id'), 'dedup_execution_action_audits', ['id'], unique=False)
    op.create_index(op.f('ix_dedup_execution_action_audits_plan_action_id'), 'dedup_execution_action_audits', ['plan_action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dedup_execution_action_audits_plan_action_id'), table_name='dedup_execution_action_audits')
    op.drop_index(op.f('ix_dedup_execution_action_audits_id'), table_name='dedup_execution_action_audits')
    op.drop_index(op.f('ix_dedup_execution_action_audits_execution_id'), table_name='dedup_execution_action_audits')
    op.drop_index(op.f('ix_dedup_execution_action_audits_document_id'), table_name='dedup_execution_action_audits')
    op.drop_table('dedup_execution_action_audits')
    op.drop_index(op.f('ix_dedup_executions_plan_id'), table_name='dedup_executions')
    op.drop_index(op.f('ix_dedup_executions_id'), table_name='dedup_executions')
    op.drop_index(op.f('ix_dedup_executions_authorization_id'), table_name='dedup_executions')
    op.drop_table('dedup_executions')
    # ### end Alembic commands ###
    # op.drop_table() has no knowledge of the enum types its dropped
    # columns used - unlike op.create_table(), which auto-emits CREATE
    # TYPE, dropping a table never auto-emits DROP TYPE. Only these two
    # types are exclusively owned by the tables dropped above (unlike
    # dedup_plan_action_type, shared with dedup_execution_plan_actions,
    # which must survive this downgrade untouched).
    postgresql.ENUM(name='dedup_execution_action_result').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='dedup_execution_status').drop(op.get_bind(), checkfirst=True)
