"""add execution audit crash-recovery representation

Revision ID: 6189c90d31a8
Revises: 16a7cf136058
Create Date: 2026-09-12 16:09:20.957608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6189c90d31a8'
down_revision: Union[str, Sequence[str], None] = '16a7cf136058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate detects the nullable-column change but NOT new enum
    # labels (a known limitation - same reason enum-value RENAMEs in
    # this codebase, e.g. migration 6af80a472ca2, are hand-written).
    # ALTER TYPE ... ADD VALUE is safe to run inside this migration's
    # transaction on Postgres 12+ as long as the new value isn't also
    # USED within the same transaction, which it isn't here.
    op.execute("ALTER TYPE dedup_execution_action_result ADD VALUE 'UNKNOWN'")
    op.execute("ALTER TYPE dedup_execution_status ADD VALUE 'NEEDS_REVIEW'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dedup_execution_action_audits', 'filesystem_mutation_occurred',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dedup_execution_action_audits', 'filesystem_mutation_occurred',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###

    # PostgreSQL has no "ALTER TYPE ... DROP VALUE" - an enum value,
    # once added, cannot be removed without recreating the type (which
    # would require dropping every column that uses it, including
    # ones this migration doesn't own). The enum values from upgrade()
    # are deliberately left in place on downgrade; only the column
    # nullability is reversed above. This mirrors standard practice for
    # this exact PostgreSQL limitation and is intentional, not an
    # oversight.
