"""add dedup execution plan tables

Revision ID: 8eebb7e854fb
Revises: 6af80a472ca2
Create Date: 2026-09-12 12:55:15.431358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eebb7e854fb'
down_revision: Union[str, Sequence[str], None] = '6af80a472ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedup_execution_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('canonical_document_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_source_path', sa.Text(), nullable=False),
    sa.Column('canonical_observed_exists', sa.Boolean(), nullable=False),
    sa.Column('canonical_observed_content_hash', sa.String(length=64), nullable=True),
    sa.Column('canonical_observed_file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('GENERATED', name='dedup_plan_status'), server_default='GENERATED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['duplicate_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dedup_execution_plans_id'), 'dedup_execution_plans', ['id'], unique=False)
    op.create_index(op.f('ix_dedup_execution_plans_review_id'), 'dedup_execution_plans', ['review_id'], unique=False)
    op.create_table('dedup_execution_plan_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('DELETE', name='dedup_plan_action_type'), server_default='DELETE', nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('target_document_id', sa.String(length=36), nullable=False),
    sa.Column('target_path', sa.Text(), nullable=False),
    sa.Column('observed_exists', sa.Boolean(), nullable=False),
    sa.Column('observed_content_hash', sa.String(length=64), nullable=True),
    sa.Column('observed_file_size', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['dedup_execution_plans.id'], ),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dedup_execution_plan_actions_document_id'), 'dedup_execution_plan_actions', ['document_id'], unique=False)
    op.create_index(op.f('ix_dedup_execution_plan_actions_id'), 'dedup_execution_plan_actions', ['id'], unique=False)
    op.create_index(op.f('ix_dedup_execution_plan_actions_plan_id'), 'dedup_execution_plan_actions', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dedup_execution_plan_actions_plan_id'), table_name='dedup_execution_plan_actions')
    op.drop_index(op.f('ix_dedup_execution_plan_actions_id'), table_name='dedup_execution_plan_actions')
    op.drop_index(op.f('ix_dedup_execution_plan_actions_document_id'), table_name='dedup_execution_plan_actions')
    op.drop_table('dedup_execution_plan_actions')
    op.drop_index(op.f('ix_dedup_execution_plans_review_id'), table_name='dedup_execution_plans')
    op.drop_index(op.f('ix_dedup_execution_plans_id'), table_name='dedup_execution_plans')
    op.drop_table('dedup_execution_plans')
    # ### end Alembic commands ###
