"""add duplicate review tables

Revision ID: a7ad86ac80d3
Revises: f96a9d082b1b
Create Date: 2026-09-12 12:04:45.558859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7ad86ac80d3'
down_revision: Union[str, Sequence[str], None] = 'f96a9d082b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT', 'NEAR', name='duplicate_match_type'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='duplicate_review_status'), server_default='PENDING', nullable=False),
    sa.Column('reviewer_decision', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_reviews_content_hash'), 'duplicate_reviews', ['content_hash'], unique=False)
    op.create_index(op.f('ix_duplicate_reviews_id'), 'duplicate_reviews', ['id'], unique=False)
    op.create_table('duplicate_review_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('PROPOSED_CANONICAL', 'DUPLICATE', name='duplicate_review_member_role'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['duplicate_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'document_id', name='uq_duplicate_review_members_review_id_document_id')
    )
    op.create_index(op.f('ix_duplicate_review_members_document_id'), 'duplicate_review_members', ['document_id'], unique=False)
    op.create_index(op.f('ix_duplicate_review_members_id'), 'duplicate_review_members', ['id'], unique=False)
    op.create_index(op.f('ix_duplicate_review_members_review_id'), 'duplicate_review_members', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duplicate_review_members_review_id'), table_name='duplicate_review_members')
    op.drop_index(op.f('ix_duplicate_review_members_id'), table_name='duplicate_review_members')
    op.drop_index(op.f('ix_duplicate_review_members_document_id'), table_name='duplicate_review_members')
    op.drop_table('duplicate_review_members')
    op.drop_index(op.f('ix_duplicate_reviews_id'), table_name='duplicate_reviews')
    op.drop_index(op.f('ix_duplicate_reviews_content_hash'), table_name='duplicate_reviews')
    op.drop_table('duplicate_reviews')
    # ### end Alembic commands ###
