"""add dedup plan authorization table

Revision ID: d0ac67db7d95
Revises: 8eebb7e854fb
Create Date: 2026-09-12 13:17:43.036364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0ac67db7d95'
down_revision: Union[str, Sequence[str], None] = '8eebb7e854fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedup_plan_authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AUTHORIZED', 'REVOKED', name='dedup_plan_authorization_status'), server_default='AUTHORIZED', nullable=False),
    sa.Column('validity_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('authorized_by', sa.Text(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['dedup_execution_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dedup_plan_authorizations_id'), 'dedup_plan_authorizations', ['id'], unique=False)
    op.create_index(op.f('ix_dedup_plan_authorizations_plan_id'), 'dedup_plan_authorizations', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dedup_plan_authorizations_plan_id'), table_name='dedup_plan_authorizations')
    op.drop_index(op.f('ix_dedup_plan_authorizations_id'), table_name='dedup_plan_authorizations')
    op.drop_table('dedup_plan_authorizations')
    # ### end Alembic commands ###
